- name: gather facts
  hosts: local
  connection: local

#ansible collects the info or target server before its executes others

  tasks:
  - name: facts
    ansible.builtin.debug:
      msg: "{{ ansible_facts}}"

