- name: check the facts
  hosts: local
  connection: local
  tasks":
    - name: install and check the nginx
      ansible.builtin.dnf:
        name: nginx
        state: latest
      when: ansible_os_family == "Redhat"
      
    - name: install and check the nginx
      ansible.builtin.dnf:
        name: nginx
        state: latest
      when: ansible_os_family == "Debian"