- name: check the facts
  hosts: local
  connection: local
  becoome: yes

  tasks:
  - name: install and check the nginx
    ansible.builtin.dnf:
      name: nginx
      state: latest
    when: ansible_os_family == "RedHat"

  - name: install and check the nginx
    ansible.builtin.dnf:
      name: nginx
      state: latest
    when: ansible_os_family == "Debian"



# - name: check the facts
#   hosts: local
#   connection: local
#   become: yes
#   gather_facts: true

#   tasks:
#     - name: install nginx on RedHat-based systems
#       ansible.builtin.dnf:
#         name: nginx
#         state: latest
#       when: ansible_facts['os_family'] == "RedHat"

#     - name: install nginx on Debian-based systems
#       ansible.builtin.apt:
#         name: nginx
#         state: latest
#         update_cache: yes
#       when: ansible_facts['os_family'] == "Debian"